### ISSUE TITLE
Python 3.7 vs 3.8

### ISSUE THREAD

**Issue by KyleM4t1qbit** [yang-song/score_sde_pytorch#16]
Not an issue (I suppose it could be an issue with the _documentation_), but putting this here in case it helps anyone else:

Running this with Python 3.7 resulted in a segmentation fault during the JIT compilation of the Pytorch C++ extensions.

Using Python 3.8 works without issue (using all packages in `requirements.txt`). 

Hope this helps someone else.

**Comment by mo666666** [comment]
Thank you very much! It is quite kind of you! I try almost all the versions for Pytorch and none of them works. Finally, the problems are solved after replacing python 3.7 with python 3.8.

**Comment by KeepNoob** [comment]
> Thank you very much! It is quite kind of you! I try almost all the versions for Pytorch and none of them works. Finally, the problems are solved after replacing python 3.7 with python 3.8.

Hi, I am struggling with the environment setup would you let me know what is your environment package version like the torch, tensorflow-probability and how you install it as I followed the `pip install -r requirment.txt` it always came with error.
Thanks.

**Comment by 1808030112** [comment]
Hello, I'm sorry to bother you. I am currently in Python 3.8.18  , but I still encounter import errors. May I ask which version of Python you are referring to.
ImportError: cannot import name 'ParamSpec' from 'typing_extensions'

**Comment by mengchuangji** [comment]
I have the same problem. I have tried different python versions.
